apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trusted-artifact-signer-triggerbinding
spec:
  params:
    - name: fulcio-url
      value: https://fulcio.apps.open-svc-sts.k1wl.p1.openshiftapps.com/
    - name: fulcio-crt-pem-url
      value: https://tuf.apps.open-svc-sts.k1wl.p1.openshiftapps.com/targets/fulcio_v1.crt.pem
    - name: rekor-url
      value: https://rekor.apps.open-svc-sts.k1wl.p1.openshiftapps.com/
    - name: issuer-url
      value: https://keycloak-keycloak-system.apps.open-svc-sts.k1wl.p1.openshiftapps.com/auth/realms/sigstore
    - name: tuf-mirror
      value: https://tuf.apps.open-svc-sts.k1wl.p1.openshiftapps.com/
    - name: tuf-root
      value: https://tuf.apps.open-svc-sts.k1wl.p1.openshiftapps.com/root.json
    - name: rekor-public-key
      value: https://tuf.apps.open-svc-sts.k1wl.p1.openshiftapps.com/targets/rekor.pub
    - name: ctfe-public-key
      value: https://tuf.apps.open-svc-sts.k1wl.p1.openshiftapps.com/targets/ctfe.pub
