apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  labels:
    app: sso
  name:
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    email: 
    enabled: true
    emailVerified: true
    credentials:
      - type: password
        value: 
    firstName: 
    lastName: 
    username:
