apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: securesign-pipelines-demo
resources:
  - build-and-sign-pipeline.yaml
  - build-and-sign-triggerbinding.yaml
  - build-and-sign-triggertemplate.yaml
  - build-and-sign-el.yaml
  - build-and-sign-el-route.yaml
  - grpereir-securesign-demo-sealed-secret.yaml
  - tektonChain.yaml
